Assignment-software-engineering/.gitignore, Assignment-software-engineering/.idea/.gitignore, Assignment-software-engineering/.idea/misc.xml, Assignment-software-engineering/.idea/modules.xml, Assignment-software-engineering/.idea/vcs.xml, Assignment-software-engineering/Assignment-software-engineering.iml, Assignment-software-engineering/src/Main.java
I put it in the directory of the repository and made a basic program
=> this is the file I made for assignment 1

README.md
=> Fixes via Antonio's Review

annotations/DataStorageAPI.java
First version for the data storage api. Might need some checks on referencing the ProcessAPI correctly *hint hint*
=> DataStorage API V. 1

annotations/DataStorageAPI.java
=> Fixes for Antonio's Review

annotations/src/project/annotations/DataStorage/StorageComputeAPI.java, annotations/src/project/annotations/DataStorage/StorageComputeAPIPrototype.java
DataStorage API rearranged into a folder under annotations alongside Network API. Should be referencing with annotations>ProcessAPI, etc. in this hierarchy
=> Finalized DataStorage API

src/project/APIs/API-DataConnecions/ConceptualAPIPrototype.java, src/project/APIs/API-DataConnecions/DataStorage.java, src/project/APIs/API-DataConnecions/Delimiter.java, src/project/APIs/API-DataConnecions/Main.java, src/project/APIs/API-DataConnecions/RetriveData.java, src/project/APIs/API-DataConnecions/StoreData.java, src/project/APIs/API-DataConnecions/UserInput.java, src/project/APIs/API-DataConnecions/api.java, src/project/APIs/DataStorage/StorageComputeAPI.java, src/project/APIs/DataStorage/StorageComputeAPIPrototype.java, src/project/APIs/NetworkAPI/AskUser.java, src/project/APIs/NetworkAPI/Screen.java, src/project/APIs/NetworkAPI/SendInfo.java, src/project/APIs/NetworkAPI/ValidInfo.java, src/project/APIs/NetworkAPI/Window.java, src/project/annotations/ConceptualAPI.java, src/project/annotations/ConceptualAPIPrototype.java, src/project/annotations/NetworkAPI.java, src/project/annotations/NetworkAPIPrototype.java, src/project/annotations/ProcessAPI.java, src/project/annotations/ProcessAPIPrototype.java, test/project/annotations/Assignment2StructureTest.java, test/project/annotations/Utils.java
Some key issues addressed:
- build.gradle assumes the annotations and APIs are under src not annotations/src (FIXED)
- test folder should be in the main directory, outside src
- All 3 APIs worked on are now under 1 key folder (APIs)
Some things to keep in mind now:
- Make sure your respective APIs code addresses this directory change, so make sure they are able to run now assuming its no longer annotations/src rather just src and also the given API annotations (given by the professor) is now its own folder and I moved all APIs into a folder called "APIs" for these APIs are separated from the **Prototype APIs**
=> Restructured Project (Final PLEASE READ)

test/project/annotations/InMemoryDataStore.java
Test-only implementation of the DataStore interface, processing input from an in-memory input configuration and writing the results to an in-memory output configuration.
=> [Added] InMemoryDataStore

test/project/annotations/TestStorageComputeAPI.java
Testing the StorageComputeAPI.java file, via Mockito testing
=> [TEST ADDED] TestStorageComputeAPI.java

src/project/APIs/DataStorage/DataStorageAPI.java
Added (2/2) DataStorage as per instruction alongside the prototype API
=> [Implement] Create DataStorageAPI.java

src/project/APIs/DataStorage/DataStorageAPIPrototype.java
Added (1/2) DataStorageAPI, this one is the prototype as per instruction
=> [IMPLEMENT] Create DataStorageAPIPrototype.java

src/project/apis/datastorage/StorageStorageComputeAPIPrototype.java
This is the prototype that handles the writing of data, etc. which will be tested.
=> [Added] StorageStorageComputeAPIPrototype

test/project/annotations/TestDataStorageAPI.java
Testing for my DataStorageAPI file
=> [Added] TestDataStorageAPI

ImplementDataStorage/src/ImplementDataStorage.java, testrun/test/ExampleTest.java
=> implementComputeData

test/project/annotations/TestDigitalRootPersistenceAPI.java
Old reviewed test, just renamed and readied
=> [Renamed] TestDigitalRootPersistenceAPI.java

src/project/apis/networkapi/AskUser.java
Done via pair programming. Had old directory in the header.
=> [Old Fix] AskUser.java

src/project/apis/networkapi/Screen.java
Done via pair programming. Had old directory in the header.
=> [Fixed] Screen.java

src/project/apis/networkapi/ValidInfo.java
Done via pair programming. Had old directory in the header.
=> [FIX] ValidInfo

src/project/apis/networkapi/Window.java
Done via pair programming. Had old directory in the header.
=> [FIX] Window.java

src/project/apis/networkapi/ImplementNetworkAPI.java
Done via pair programming (W/ Chris) Unable to access proper coding space so was done through computer-phone communication.
=> [Added] ImplementNetworkAPI

src/project/apis/api-dataconnections/ImplementDigitalRootPersistenceAPI.java, test/project/annotations/ComputeEngineIntegrationTest.java
Empty API implementation for computation API
=> [Added] ImplementDigitalRootPersistenceAPI.java

test/project/annotations/CompueEngineIntegrationTest.java
Original pull request for this had a branch error, but after, still existed. (Via. pair pro.)
=> [Readd] Create CompueEngineIntegrationTest.java

src/project/apis/datastorage/DataStorageAPI.java
package header had old directory reference.
=> [Fixed] DataStorageAPI

src/project/apis/datastorage/DataStorageAPIPrototype.java
Contained old directory on the imports.
=> [Updated] DataStorageAPIPrototype

test/project/annotations/TestScreen.java
Done via pair programming (Chris) --> phone -> computer communication, unable to access a proper coding space.
=> [Test] TestScreen.java

test/project/annotations/TestImplementNetworkAPI.java
Done via pair programming (Chris) phone-computer communication, unable to access a coding space.
=> [Test] TestImplementNetworkAPI.java

src/project/apis/datastorage/ImplementDataStorage.java
Was referencing "DataStore" but meant to be "DataStorage" for this is the API handling the data manipulation for storing.
=> [Revised] ImplementDataStorage

src/project/apis/api-dataconnections/ImplementDigitalRootPersistenceAPI.java
Improper import directory, causing gradle error.
=> [FIX] ImplementDigitalRootPersistenceAPI.java

src/project/apis/datastorage/ImplementDataStorage.java
=> [Quick Fix] ImplementDataStorage.java

src/project/apis/networkapi/ImplementNetworkAPI.java
=> [Quick Fix] ImplementNetworkAPI.java

checkstyle_checks.xml
Checkstyle is being triggered when imporiting project.annotations. (All java classes) which is odd.
=> [Packagename Leniency] checkstyle_checks.xml

src/project/annotations/ProcessAPIPrototype.java
package project.annotations;
added at the top. (Gradle error)
=> [Quick Fix] ProcessAPIPrototype.java

src/project/apis/datastorage/StorageComputeAPI.java
Improper imports causing gradle errors
=> [Quick Fix] Improper imports

test/project/annotations/ComputeEngineIntegrationTest.java
Improper reference of old data-connections folder
=> [Quick Fix] ComputeEngineIntegrationTest.java

test/project/annotations/InMemoryInputConfig.java
=> [Quick Fix] InMemoryInputConfig.java

test/project/annotations/InMemoryOutputConfig.java
=> [Quick Fix] InMemoryOutputConfig.java

test/project/annotations/InMemoryInputConfig.java
Issues with InputConfig but it's not an existing interface, so I added a mock interface in the file for now.
=> [File Fix] InMemoryInputConfig.java

test/project/annotations/InMemoryDataStore.java
Contained no reference/interface to the output/input configs which are subfiles for testing but for now will include in the file.
=> [File Fix] InMemoryDatastore

test/project/annotations/TestImplementNetworkAPI.java
Fixed smoke testing with mockito for it caused gradle error
=> [File Fix] TestImplementNetworkAPI.java

test/project/annotations/InMemoryOutputConfig.java
Testing parameters fixed and included
=> [File Fix] InMemoryOutputConfig.java

test/project/annotations/TestScreen.java
Missing imports of the networkapi
=> [File Fix] TestScreen.java

test/project/annotations/InMemoryOutputConfigTest.java
=> [Quick Fix] InMemoryOutputConfigTest.java

test/project/annotations/InMemoryDataStore.java
=> [Import Fix] InMemoryDataStore.java

test/project/annotations/InputConfig.java
Added proper imports and extra method class
=> [Code Restructure] InputConfig.java

test/project/annotations/InMemoryInputConfig.java
=> [Code Fix] InMemoryInputConfig.java

test/project/annotations/InMemoryDataStore.java
Proper imports and fixed methods
=> [Quick Fix] InMemoryDataStore.java

test/project/annotations/Assignment2StructureTest.java
This test was checking for networkapi and its prototype to be in some deep separate folder, this just makes it so we can keep the 2 files with the other files under src/annotations
=> [Minor Alter] Assignment2StructureTest.java

.vscode/settings.json, Assignment-software-engineering/src/Main.java, src/project/Main.java, src/project/annotations/ConceptualAPI.java, src/project/annotations/ConceptualAPIPrototype.java, src/project/annotations/NetworkAPI.java, src/project/annotations/NetworkAPIPrototype.java, src/project/annotations/ProcessAPI.java, src/project/annotations/ProcessAPIPrototype.java
Main.java was not able to be read by the directory so I moved it src/ for testing the Test files.
=> MovedMainJava

.vscode/settings.json, Assignment-software-engineering/src/Main.java, src/project/Main.java, src/project/annotations/ConceptualAPI.java, src/project/annotations/ConceptualAPIPrototype.java, src/project/annotations/NetworkAPI.java, src/project/annotations/NetworkAPIPrototype.java, src/project/annotations/ProcessAPI.java, src/project/annotations/ProcessAPIPrototype.java
Main.java moved along with other file realignment.
=> HotFix (Main.java)

src/project/apis/datastorage/ImplementDataStorage.java
read and write user specific files.
=> [ReAdded] ImplementDataStorage

.github/workflows/Gradle.yml
=> [Reset] Gradle.yml

test/project/annotations/TestImplementNetworkAPI.java
=> [Hot Fix] TestImplementNetworkAPI.java

src/project/apis/computeapi/ImplementDigitalRootPersistenceAPI.java, src/project/apis/networkapi/ImplementNetworkAPI.java, src/project/apis/networkapi/TestingForErrorsProcess.java, test/project/annotations/TestImplementNetworkAPI.java
Add exception handling to prevent uncaught exceptions from reaching any process or network boundaries - this exception handling should take care of both expected exceptions (explicitly declared checked exceptions) and unexpected exceptions (runtime exceptions that aren't deliberately thrown by your code), and it should translate them into a response that clients of the API can identify as an error situation (either with an explicit error return status or a sentinel value).
Add at least one integration test that checks your exception handling logic.
=> Added integration and exception

.gitignore
According to the slides, we should be ignoring the generated files created by proto.
=> .gitignore (To ignore generated Proto Files)

build.gradle, src/main/proto/datastorage.proto, src/project/Main.java, src/project/apis/computeapi/FastDigitalRootPersistenceAPI.java, src/project/apis/datastorage/DataStorageApiGrpcClient.java, src/project/apis/datastorage/DataStorageApiGrpcServer.java, src/project/apis/networkapi/FileIOHandler.java, test/project/annotations/FileIOHandlerTest.java
Task 1, 2. Improved DigitalRootPersistence by 10% and added second implementation for this.
=> Fast DigitalRootPersistence (10% Improvement)
